version: '3.9'

services:
  dbpostgres:
    container_name: dbpostgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bsb
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    image: postgres